### ISSUE TITLE
continueUrl not implemented

### ISSUE THREAD

**Issue by przemek1991pl** [django-getpaid/django-getpaid-payu#3]
* django-getpaid version: 2.2.1
* django-getpaid-payu version: 0.2.0
* Django version: 3.0.6
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description

As far as I checked your code. continueUrl is not implemented at all.

It would be great to implement it. eg. 127.0.0.1:8000/order-complete/<uuid:order_pk>/ or something similar.

If it is implemented please share some information how to do it.

Thanks :)
Przemek

**Comment by dekoza** [comment]
Thanks. This repo is still a work-in-progress despite being mentioned in the main repo. I'm returning to this project and right now I'm scouting forks for fixes since nobody posted any pull requests :wink: I think I saw this issue fixed. I know it's been over a year since you posted it, sorry.

**Comment by dekoza** [comment]
Fixed in a5501ba, published on pypi.
